apiVersion: apps/v1
kind: Deployment
metadata:
  name: c-nginx-deployment
  labels:
    app: c-nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: c-nginx
  template:
    metadata:
      labels:
        app: c-nginx
    spec:
      containers:
      - name: c-nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80